###get all
GET http://localhost:3001/api/blogs/

###add NEW person
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Pinhead Larry",
    "author": "Dirty Dan", 
    "url": "google.com",
    "likes": "99999999999"
}